### ISSUE TITLE
Running into error with as111.py on a Pi Zero

### ISSUE THREAD

**Issue by Cromford** [Heckie75/sync-philips-as111#1]
Trying to get the script running on a Raspberry Pi Zero (Buster Lite). I managed to successcully connect the Zero to the AS111 and are able to send a sound to the dock via paplay. When starting the script, I always run into the following error message:
Traceback (most recent call last):

  File "./as111.py", line 908, in <module>
    as111 = AS111()
  File "./as111.py", line 87, in __init__
    self._request_a2dp_state()
  File "./as111.py", line 240, in _request_a2dp_state
    _device["sink"] = l[7:-1]
TypeError: 'NoneType' object does not support item assignment

When I check the sinks with pacmd list-sinks I am getting the output in the attached file.

Not sure if there is something wrong with my bluetooth / pulseaudio config or if the script is no longer compatible with the latest software - have run a full apt-get update / upgrade.

Any hints on how to solve the issue are highly welcome. :-)

[pacmd list-sinks.txt](https://github.com/Heckie75/sync-philips-as111/files/8457062/pacmd.list-sinks.txt)

**Comment by Heckie75** [comment]
@Cromford 
Could you please send me output of the following commands:
```
heckie@heckies-nuc:~$ bluetoothctl
Agent registered
[CHG] Controller 00:1A:7D:DA:71:13 Pairable: yes
[CHG] Controller 14:F6:D8:D4:1F:F1 Pairable: yes
[bluetooth]# select 00:1A:7D:DA:71:13
Controller 00:1A:7D:DA:71:13 heckies-nuc [default]
[bluetooth]# devices
Device 00:1D:DF:52:F1:91 PHILIPS AS111
...
```

In my case there are two controllers. Use the _select_ statement with the mac address according the address of your controller. repeat the _devices_ command for each controller.

**Comment by Cromford** [comment]
@Heckie75 
Many thanks for the quick reply - here is what I've got:

pi@raspberrypi:~ $ bluetoothctl
Agent registered
[bluetooth]# list
Controller B8:27:EB:E8:7E:AD raspberrypi [default]
[bluetooth]# select B8:27:EB:E8:7E:AD
[bluetooth]# devices
Device 48:68:4D:47:07:12 48-68-4D-47-07-12
Device 00:1D:DF:B5:00:D0 PHILIPS AS111
Device 48:E6:95:03:96:CE 48-E6-95-03-96-CE
Device 7F:AA:2B:A2:88:E7 7F-AA-2B-A2-88-E7
Device 6C:39:AA:39:78:F0 6C-39-AA-39-78-F0
Device 54:97:5E:FD:30:D5 54-97-5E-FD-30-D5
Device 6F:37:C1:1C:DA:EF 6F-37-C1-1C-DA-EF
Device F5:1C:90:DC:58:2A F5-1C-90-DC-58-2A
Device C8:E0:EB:43:A4:B6 C8-E0-EB-43-A4-B6
Device 7B:98:4B:75:86:16 7B-98-4B-75-86-16
Device 40:99:5F:81:82:44 40-99-5F-81-82-44
Device 26:14:09:C2:03:C4 26-14-09-C2-03-C4
Device 64:F7:BF:BC:98:28 64-F7-BF-BC-98-28
Device F0:B3:EC:14:F8:51 F0-B3-EC-14-F8-51
Device 78:1D:58:F8:45:F8 78-1D-58-F8-45-F8
Device 35:5C:2B:DE:B1:65 35-5C-2B-DE-B1-65
Device 6A:CB:58:5A:B9:70 6A-CB-58-5A-B9-70
Device 72:90:DC:AB:A4:AB 72-90-DC-AB-A4-AB
Device 52:6E:8B:03:99:F0 52-6E-8B-03-99-F0
Device 27:3F:15:79:AB:56 27-3F-15-79-AB-56
Device 7D:0F:16:43:0C:B3 7D-0F-16-43-0C-B3
Device 68:9B:21:78:2D:EF 68-9B-21-78-2D-EF
Device 58:3B:71:4D:CD:EA 58-3B-71-4D-CD-EA
[bluetooth]# info 00:1D:DF:B5:00:D0
Device 00:1D:DF:B5:00:D0 (public)
	Name: PHILIPS AS111
	Alias: PHILIPS AS111
	Class: 0x00240404
	Icon: audio-card
	Paired: no
	Trusted: no
	Blocked: no
	Connected: no
	LegacyPairing: yes
[bluetooth]# pair 00:1D:DF:B5:00:D0
Attempting to pair with 00:1D:DF:B5:00:D0
[CHG] Device 00:1D:DF:B5:00:D0 Connected: yes
[CHG] Device 00:1D:DF:B5:00:D0 UUIDs: 00001101-0000-1000-8000-00805f9b34fb
[CHG] Device 00:1D:DF:B5:00:D0 UUIDs: 0000110b-0000-1000-8000-00805f9b34fb
[CHG] Device 00:1D:DF:B5:00:D0 UUIDs: 0000110e-0000-1000-8000-00805f9b34fb
[CHG] Device 00:1D:DF:B5:00:D0 ServicesResolved: yes
[CHG] Device 00:1D:DF:B5:00:D0 Paired: yes
Pairing successful
[CHG] Device 00:1D:DF:B5:00:D0 ServicesResolved: no
[CHG] Device 00:1D:DF:B5:00:D0 Connected: no
[CHG] Device 00:1D:DF:B5:00:D0 Connected: yes
[CHG] Device 00:1D:DF:B5:00:D0 Connected: no
[bluetooth]# trust 00:1D:DF:B5:00:D0
[CHG] Device 00:1D:DF:B5:00:D0 Trusted: yes
Changing 00:1D:DF:B5:00:D0 trust succeeded
[CHG] Device 00:1D:DF:B5:00:D0 Connected: yes
[CHG] Device 00:1D:DF:B5:00:D0 UUIDs: 00001101-0000-1000-8000-00805f9b34fb
[CHG] Device 00:1D:DF:B5:00:D0 UUIDs: 0000110b-0000-1000-8000-00805f9b34fb
[CHG] Device 00:1D:DF:B5:00:D0 UUIDs: 0000110d-0000-1000-8000-00805f9b34fb
[CHG] Device 00:1D:DF:B5:00:D0 UUIDs: 0000110e-0000-1000-8000-00805f9b34fb
[PHILIPS AS111]# connect 00:1D:DF:B5:00:D0
Attempting to connect to 00:1D:DF:B5:00:D0
[CHG] Device 00:1D:DF:B5:00:D0 ServicesResolved: yes
Connection successful
[PHILIPS AS111]# info 00:1D:DF:B5:00:D0
Device 00:1D:DF:B5:00:D0 (public)
	Name: PHILIPS AS111
	Alias: PHILIPS AS111
	Class: 0x00240404
	Icon: audio-card
	Paired: yes
	Trusted: yes
	Blocked: no
	Connected: yes
	LegacyPairing: yes
	UUID: Serial Port               (00001101-0000-1000-8000-00805f9b34fb)
	UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
	UUID: Advanced Audio Distribu.. (0000110d-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
[PHILIPS AS111]# 

I ran into a problem earlier with the latest release of Buster - now I am back on a fresh install of 2022-01-28-raspios-buster-armhf-lite. When I run pacmd list-sinks now I only get 1 sink (bluez_sink.00_1D_DF_B5_00_D0.a2dp_sink).

**Comment by penguin86** [comment]
Hello, I have the same issue on Ubuntu 22.04.4 on a x86_64 machine:
```
➜  ~ ~/opt/sync-philips-as111/as111.py - sync vol 30
Traceback (most recent call last):
  File "/home/danieleverducci/opt/sync-philips-as111/as111.py", line 908, in <module>
    as111 = AS111()
  File "/home/danieleverducci/opt/sync-philips-as111/as111.py", line 87, in __init__
    self._request_a2dp_state()
  File "/home/danieleverducci/opt/sync-philips-as111/as111.py", line 240, in _request_a2dp_state
    _device["sink"] = l[7:-1]
TypeError: 'NoneType' object does not support item assignment
➜  ~ bluetoothctl
Agent registered
[CHG] Controller 20:C1:9B:AC:EE:18 Pairable: yes
[MX Master 3]# devices
Device 78:CC:95:77:57:2C Nutella Speaker
Device FC:14:6E:F3:76:07 MX Master 3
Device 00:1D:DF:52:38:70 PHILIPS AS111
Device 00:00:AB:BD:CE:86 Fairphone Earbuds
Device F4:EE:25:EE:43:A4 BT5.0 KB
Device B4:EE:25:ED:42:A4 BT3.0 KB
Device 1F:10:05:A3:87:C4 Bamboo light speaker
Device EA:0A:EF:DA:A5:C0 MOTION IN EAR
Device 20:74:CF:4E:3A:88 Titanium by AfterShokz
[MX Master 3]# info 00:1D:DF:52:38:70
Device 00:1D:DF:52:38:70 (public)
	Name: PHILIPS AS111
	Alias: PHILIPS AS111
	Class: 0x00240404
	Icon: audio-headset
	Paired: yes
	Trusted: yes
	Blocked: no
	Connected: yes
	LegacyPairing: no
	UUID: Serial Port               (00001101-0000-1000-8000-00805f9b34fb)
	UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	UUID: Advanced Audio Distribu.. (0000110d-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
[CHG] Controller 20:C1:9B:AC:EE:18 Discovering: yes
[CHG] Controller 20:C1:9B:AC:EE:18 Discoverable: yes
[NEW] Device 19:04:0D:A4:52:C2 19-04-0D-A4-52-C2
[CHG] Device 19:04:0D:A4:52:C2 RSSI: -78
[CHG] Controller 20:C1:9B:AC:EE:18 Discoverable: no
[CHG] Device 19:04:0D:A4:52:C2 RSSI is nil
[DEL] Device 19:04:0D:A4:52:C2 19-04-0D-A4-52-C2
[CHG] Controller 20:C1:9B:AC:EE:18 Discovering: no
[MX Master 3]# 
```
The device is connected and works as audio device, but the script fails to communicate with it.
Any hints on how to fix? Thank you!

**Comment by Heckie75** [comment]
@penguin86 
I'm not able to help you by using a real device since I don't have any AS111 anymore. 

The errror occurs during parsing the out put of this command:
```
$ pacmd list-sinks
```

In your case there must be a line like this:
```
name: <bluez_sink.00_1D_DF_52_38_70.a2dp_sink>
```

Is there such a line or does it look differently?

What happens if you use the script by using the mac address like 
```
~/opt/sync-philips-as111/as111.py 00:1D:DF:52:38:70 sync vol 30
```
